# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Neppari
tagline:          'Neuropsykiatrista valmennusta Tampereella'
description:      'Neuropsykiatrista valmennusta Tampereella'
tagline-short:    'Neuropsykiatrisen valmennuksen paikka'
baseurl:          /
siteurl:          http://neppari.net

contact:
  name:           'Niina Piira'
  address:        'Oravanpolku 5 A, Tampere'
  phone:          '040 934 9954'
  email:          'niina@neppari.net'
  email4form:     'nepparinet+yhteydenottosivuilta@gmail.com'
  page:           '/ota-yhteytta'

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

sass:
  sass_dir:       css

prose:
  ignore:
    - /_includes
    - /_layouts
    - /_sass
    - /assets
    - /css
    - /fonts
    - /public
    - .gitignore
    - 404.html
    - CNAME
    - Gemfile
    - Gemfile.lock
    - LICENCE
    - README.md
    - neppari.sublime-project
  metadata:
    "":
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "Sivun otsikko"
          placeholder: "Kirjoita otsikko tähän"
      - name: "link-title"
        field:
          element: "text"
          label: "Valikkolinkin teksti"
          placeholder: "Tätä ei ole pakko täyttää"
      - name: "navigation-order"
        field:
          element: "number"
          label: "Järjestys linkkilistassa"
          help: "Pienempi numero tarkoittaa, että linkki nousee korkeammalle vasemman reunan listalla"
          value: 50
      - name: "published"
        field:
          element: "checkbox"
          label: "Onko sivu julkaistu?"
          value: false
      - name: "polaroid"
        field:
          element: "text"
          label: "Polaroid-pikkukuvan osoite"
          placeholder: "Tätä ei ole pakko täyttää"
      - name: "forms"
        field:
          element: "checkbox"
          label: "Onko tämä lomakesivu?"
          value: false