# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Neppari
tagline:          'Neuropsykiatrista valmennusta Tampereella'
description:      'Neuropsykiatrista valmennusta Tampereella'
tagline-short:    'Neuropsykiatrisen valmennuksen paikka'
baseurl:          /
siteurl:          http://neppari.net

contact:
  name:           'Niina Piira'
  address:        'Oravanpolku 5 A, Tampere'
  phone:          '040 934 9954'
  email:          'niina@neppari.net'
  email4form:     'nepparinet+yhteydenottosivuilta@gmail.com'
  page:           '/ota-yhteytta'

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

sass:
  sass_dir:       css

prose:
  ignore:
    - /_includes
    - /_layouts
    - /_sass
    - /assets
    - /css
    - /fonts
    - /public
    - _config.yml
    - .gitignore
    - 404.html
    - CNAME
    - Gemfile
    - Gemfile.lock
    - LICENCE
    - README.md
    - neppari.sublime-project