# Setup
pre-title:        Valmennuskeskus
title:            Neppari
long-title:       'Valmennuskeskus Neppari'
tagline:          'Neuropsykiatrista valmennusta Tampereella ja Pirkanmaalla'
description:      'Neppari on neuropsykiatrisen valmennuksen paikka, jossa tarjotaan tukea henkilöille joilla on esimerkiksi ADHD, ADD, Asperger, Tourette tai lievä autismi.'
tagline-short:    'Neuropsykiatrista valmennusta Pirkanmaalla'
siteurl:          https://www.neppari.net
ry-text:          Niina Piira on Neuropsykiatriset valmentajat ry:n rekisteröity jäsen sekä hallituksen jäsen 2016–2022.
ry-link:          Katso valmennuksen yleisesite yhdistyksen sivuilta klikkaamalla tästä.
absence-notification:   false
permalink:        /blogi/:title/

plugins:
  - jekyll-sitemap

# Blog
blog:
  title:          'Nepparin napsahduksia'
  tagline:        'Valmentajan välähdyksiä voimaantumisesta'
  baseurl:        '/blogi/'
  description: >
    Blogissani käsittelen rakentavasti ja ratkaisukeskeisesti yksilön
    hyvinvointia, ihmisyyttä sekä sosiaalialaa niiden tukipilarina.
    Vaikka maailma on jo aika hieno paikka elää, on aina varaa
    parantaa.
writer:
  name:           Niina Piira
  title-1:        Neuropsykiatrinen ratkaisukeskeinen valmentaja ja lyhytterapeutti
  title-2:        Laillistettu sosionomi (AMK)
  fb-profile:     'https://www.facebook.com/niina.piira.98'
  bio: >
    Olen sosiaalialan ammattilainen, joka on yrittänyt tehdä
    maailmasta paremman jo 25 vuoden ajan. En pelkää haasteita
    enkä haastavia tilanteita. Vapaa-ajalla minut löytää yleensä
    koiran, perheeni tai ystävien seurasta.

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "blogi.md"
    values:
      layout: "blog-frontpage"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

contact:
  name:              'Niina Piira'
  address:
    sidebar-version: 'Puutarhakatu 16 B, 5.krs, TRE'
    guide-version:   'Puutarhakatu 16 B, 5. kerros, Tampere'
    street-address:  'Puutarhakatu 16'
    city:            'Tampere'
    post-number:     '33210'
    region:          'Pirkanmaa'
    country:         'Finland'
  location:
    latitude:        '61.499045'
    longitude:       '23.753037'
  google-maps-route: 'https://maps.app.goo.gl/co71AXnN3C8ccYE27'
  google-maps-embed: '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d842.7539745833675!2d23.752650635629777!3d61.49870330840465!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x468ed8af3c10ab4d%3A0x715adae124858cc3!2sPuutarhakatu%2016%2C%2033210%20Tampere!5e1!3m2!1sen!2sfi!4v1744900270625!5m2!1sen!2sfi" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>'
  reittiopas:        'https://reittiopas.tampere.fi/-/Puutarhakatu%2016%2C%20Tampere%3A%3A61.499045%2C23.753037'
  phone:
    finnish:         '040 934 9954'
    international:   '+358409349954'
  email:
    normal:          'niina@neppari.net'
  cv-page:           '/niina'
  page:              '/ota-yhteytta'
  fb-profile:        'https://www.facebook.com/valmennuskeskus.neppari'
  twitter-profile:   'https://twitter.com/NiinaPiira'

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

sass:
  sass_dir:       css

prose:
  ignore:
    - /_includes
    - /_layouts
    - /_sass
    - /assets
    - /css
    - /fonts
    - /public
    - /uploaded-images/.store-this-folder-in-git
    - _config.yml
    - .gitignore
    - 404.html
    - CNAME
    - Gemfile
    - Gemfile.lock
    - LICENCE
    - README.md
    - start.sh
    - neppari.sublime-project
  media: 'uploaded-images'
  metadata:
    "":
      - name: "page-title"
        field:
          element: "text"
          label: "Sivun otsikko"
          placeholder: "Kirjoita otsikko tähän"
      - name: "link-title"
        field:
          element: "text"
          label: "Linkin teksti, joka näytetään sivupalkissa"
          help: "Mikäli sivun otsikko on liian pitkä mahtuakseen sivupalkkiin, voit kirjoittaa tähän lyhyemmän linkin"
          placeholder: "Tätä ei ole pakko täyttää"
      - name: "permalink"
        field:
          element: "text"
          label: "Sivun osoitteen loppuosa"
          help: "Jos sivun osoitteen pitää olla jotain muuta kuin sen tiedostonimestä muodostettu osoite, kirjoita se tähän"
          placeholder: "Tätä ei ole pakko täyttää, eikä todennäköisesti kannatakaan"
      - name: "page-type"
        field:
          element: "select"
          label: "Sivun tyyppi"
          options:
            - name: "Tavallinen alisivu"
              value: "normal"
            - name: "Etusivu"
              value: "front-page"
            - name: "CV-sivu"
              value: "cv"
            - name: "Palautesivu"
              value: "form"
      - name: "show-in-navigation"
        field:
          element: "checkbox"
          label: "Näytetään tämä sivu sivupalkin navigaatiossa?"
          value: false
      - name: "navigation-order"
        field:
          element: "number"
          label: "Järjestys linkkilistassa"
          help: "Miten korkealle haluat tämän sivun nousevan sivupalkin linkkilistassa? Pienempi numero tarkoittaa korkeampaa sijoitusta."
          value: 50
      - name: "polaroid"
        field:
          element: "text"
          label: "Polaroid-pikkukuvan osoite"
          placeholder: "Tätä ei ole pakko täyttää"
      - name: "published"
        field:
          element: "checkbox"
          label: "Onko sivu julkaistu?"
          value: false
    "_posts":
      - name: "page-title"
        field:
          element: "text"
          label: "Blogipostauksen otsikko"
          placeholder: "Kirjoita otsikko tähän"
      - name: "published"
        field:
          element: "checkbox"
          label: "Onko sivu julkaistu?"
          value: false
