# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Neppari
tagline:          'Neuropsykiatrista valmennusta ja ammatillista tukihenkilötoimintaa Tampereella'
description:      'Neuropsykiatrista valmennusta ja ammatillista tukihenkilötoimintaa Tampereella'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Niina Piira'
  url:            https://twitter.com/mdo

contact:
  address:        Foobar 1, Tampere
  phone:          040 555 6666
  email:          foo@bar.com

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

sass:
  sass_dir:       css