[build.environment]
  JEKYLL_ENV="development"

[context.production.environment]
  JEKYLL_ENV="production"

[[redirects]]
  from = "/valmennus"
  to = "/nepsy-valmennus"
  status = 301

[[redirects]]
  from = "/etavalmennus"
  to = "/nepsy-valmennus"
  status = 301

[[redirects]]
  from = "/lyhytvalmennus"
  to = "/nepsy-valmennus"
  status = 301

[[redirects]]
  from = "/koulutus-luennot-tyopajat"
  to = "/koulutukset"
  status = 301

[[redirects]]
  from = "/ammattilaisten-valmennus"
  to = "/konsultointi"
  status = 301

[[redirects]]
  from = "/vanhempien-valmennus"
  to = "/tukea-nepsyperheille"
  status = 301
[[redirects]]
  from = "/perheohjaus-dfg"
  to = "/tukea-nepsyperheille"
  status = 301